[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/api/health"
timeout = 100
interval = 100
